language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - sys-img-armeabi-v7a-android-21
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  - secure: i6hA50B2B/wR3/FAtyd2RHTj2Kj60Q+XY9F+iLUiSt1dvMlInk1ZMRoAIR4OHWq7O8kBeqBPftnXE6HmTiHYuu5Dv9u2AStdJeNc0VAfKEV/UNfEJ/4w0aGLz0iZMWbGaRPm2+sktPbm/FXDHx7ND/Poxn68fPEvDQFBd4cUIArdk6bi+bmThh2XxiMZ2ValDNOjFAmaG5nnmayMyBkwvb6LIfM8GVC9gdJ1AOZHJOlQKb8CsJF4xnhKL3OCOlnd+x5wYZxHRybfnV9LWXIwaeE5BgC57AULXHmqaHzxGONndAbF6+8DIuFQac/HaIHAGYlfc0XL3/NedTlWXoQgYnUEBqa2D8+5fceGyWVd7q8fhgIrvyhnTLBm/QD84ElG4hnUZY1/4UbI1Ze7/GQMINDE91F2YanhIpSE8dN6pbhnyGFufdbZp17E6lwwtRmCmy6d4Yh6VUaIQl+abce2mwPapKRrn05XmedAieCJkzAXlzEsd3wg4Sdk1mUspzF/VyfPm7WvPwCeLU22kuJ4JwMvdCeq6BnDZaxEoffzueumirBk7AzchstH/NeXEOpMsevmOgPgBG5QqmS5wPi15IBObqt02gvwbF4FxfxVnmNN2JczB7yT2pmX+iXUkA7JxBGAsXJWITQNvjT9P3sEQzAjJV5O9QkxDbQr/A9B9U0=
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
notifications:
  slack:
    secure: DM7f9/+tG2pyaaijaPcdV/yqfeAnlNwusDbKuaD/WvTMBRUKWXAv/q0w+s2YUmUkoKVMQlBOqyvu5T62Jb8qGAXPP1PQnIMHHOl4IL6g70NBCtPzyzH97bl8F8Uk7fY1OYx1gmnCj2FYJ/B4wM1ZIR4nDChsoS+9BUpAlvO9OLlcC9MF/dWlpoddxktAl5+KR+Tg6AxqRMvdP5lEbiGb8GI44Z0jnkRAPRUsNDhnSZb+SgJzotLUOevTeROldGQxo0R4BiJxz5O/cyJ3bBr0ez6GdpQEiOY2Pod9RqQRRlXDMKCMHfh+8B30npGOrwSm7spCawVlu6lj4W3QzgfSiXdh5rNJ6BhjK5HXZ/+fm1OpgiB/sFwk0huYyyVkacQ+qr9Se7WsZbvZMvsHZeZfQweuFhSw0FlfkBaU6rE2frWD8JhujGM9HfdvFRmjNuHAL37cNlBS9qlV/MLpUTHIhFLStYhRdQoWuRoLiv0EjkUmo/B5zRhREIyDq+0Md1o0A6iFpE/T7qj535EkhOLwcLwbeKOT5KysOFYtNVnHBjpJ/P0nYP6V6YZ9y+tMSGmgCD2Tx1MIhpPPrFVYaKtwzbfbk8Es+XlzKh/OSPnhVgOgjPkewK7zN6PvyYAnzqx7282j1Ik91pTg6OuaOg2l9NN5o9uQh/I/27f1ZlHrs1Y=
