language: android

android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - sys-img-armeabi-v7a-android-25

jdk:
- oraclejdk8



before_install:
- chmod +x gradlew

script:
- ./gradlew build connectedCheck


notifications:
    slack: soen390cryingcorner:8N7qTrseWQDgh7PPw3T2mjKY

    notifications:
      email:
        - mohamed_2_27@hotmail.com
        - pcabro@gmail.com
        - gprattico95@gmail.com
        - aghiles_1@hotmail.com
        - ayoube.akaouch@gmail.com
        - momo_lebest@hotmail.com

on_success: always # default: change
    on_failure: always # default: always