language: android

android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - sys-img-armeabi-v7a-android-25

jdk:
- oraclejdk8



before_install:
- chmod +x gradlew

script:
- ./gradlew build connectedCheck


notifications:
  email:
    recipients:
      - mohamed_2_27@hotmail.com
      - pcabro@gmail.com
      - aghiles_1@hotmail.com
      - gprattico95@gmail.com
      - ayoube.akaouch@gmail.com
      - momo_lebest@hotmail.fr

    on_success: always # default: change
    on_failure: always # default: always