language: android

android:
  components:
  - build-tools-21.1.2
  - android-21
  - sys-img-armeabi-v7a-android-21

jdk:
- oraclejdk8

addons:
  sonarqube: true

script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN

notifications:
  slack: 'niteshpatel:$SLACK_TOKEN'
