language: android

android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - sys-img-armeabi-v7a-android-25

jdk:
- oraclejdk8



before_install:
- chmod +x gradlew

script:
- ./gradlew build connectedCheck


notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
    on_success: never # default: change
    on_failure: always # default: always