language: android

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - sys-img-armeabi-v7a-android-25

jdk:
- oraclejdk8



before_install:
- chmod +x gradlew

script:
- ./gradlew build connectedCheck


notifications:
    slack: soen390cryingcorner:8N7qTrseWQDgh7PPw3T2mjKY
