language: android

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - sys-img-armeabi-v7a-android-25

jdk:
- oraclejdk8

addons:
  sonarqube: true

before_install:
- chmod +x gradlew

script:
- ./gradlew build connectedCheck
- sonar-scanner -Dsonar.login=$SONAR_TOKEN

 notifications:
    slack: soen390cryingcorner:i7nWiZto2fkXXOn9j9J9PNCM