language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    # - sys-img-x86-android-17

addons:
  sonarqube: true
env:
  global:
    - secure: "i6hA50B2B/wR3/FAtyd2RHTj2Kj60Q+XY9F+iLUiSt1dvMlInk1ZMRoAIR4OHWq7O8kBeqBPftnXE6HmTiHYuu5Dv9u2AStdJeNc0VAfKEV/UNfEJ/4w0aGLz0iZMWbGaRPm2+sktPbm/FXDHx7ND/Poxn68fPEvDQFBd4cUIArdk6bi+bmThh2XxiMZ2ValDNOjFAmaG5nnmayMyBkwvb6LIfM8GVC9gdJ1AOZHJOlQKb8CsJF4xnhKL3OCOlnd+x5wYZxHRybfnV9LWXIwaeE5BgC57AULXHmqaHzxGONndAbF6+8DIuFQac/HaIHAGYlfc0XL3/NedTlWXoQgYnUEBqa2D8+5fceGyWVd7q8fhgIrvyhnTLBm/QD84ElG4hnUZY1/4UbI1Ze7/GQMINDE91F2YanhIpSE8dN6pbhnyGFufdbZp17E6lwwtRmCmy6d4Yh6VUaIQl+abce2mwPapKRrn05XmedAieCJkzAXlzEsd3wg4Sdk1mUspzF/VyfPm7WvPwCeLU22kuJ4JwMvdCeq6BnDZaxEoffzueumirBk7AzchstH/NeXEOpMsevmOgPgBG5QqmS5wPi15IBObqt02gvwbF4FxfxVnmNN2JczB7yT2pmX+iXUkA7JxBGAsXJWITQNvjT9P3sEQzAjJV5O9QkxDbQr/A9B9U0=" # defines SONAR_TOKEN=abcdef0123456789
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
