language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - sys-img-armeabi-v7a-android-21
jdk:
- oraclejdk8
addons:
  sonarqube: true
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
dd:
  secure: qItqGu+uv3o8SH6y0VS7cBTXA08Lr6zJ6ejRjcE8nH0gZzRClpdylehO50SgbZf2nBzXhqc61WfGCSbXxniTjug8R4o+5benn/k/vIsU4IN+WxJS8OUQiItvE2kM+07jBmg41XB2gwW7dQ9F2afBLxzvgivnNpxem08pwaW5qZAcbnCuPMlZaQXD1jE9Re5WKExM4hwUhBtzVwjuTtm1m8sUTS394eXu3MYxN5eqYkmSjpw3ocsKszMG7kIXcY18vjHyh0wZea2EIBfRXBsdDDeVivJVgZCpCiiIXvTJR7hrMLW29MLza5HwXiOoxqKGoRZgdYihbJV8BfmR5DVR+s6IghCBEUGjo6mV+a2k7AXfAb2CggQzRHyXqQv20B3AberhAX8fbcZHmfN40XnurVmgGvO2v0PFk1hbXGL5hJQAx6lc605d0XMnUp2bUmtGAL0EZg0xp2dhrQhISND4nS2s28u+XMeXtTA/EwRTAxeHr1AQGZS6vD9VKvkgkQ472/sFp8MC/GfHxxzVoZdwKisG78UXQnNGfpz6yz+endLRgwXfOQUWjVfU7tx9bMaK8xjfHAF2MCuwP5eAc/jS453TipibNjKZjwA2lxcFy4zPawrk6Bu0TU6MngkTFQ3csrmV5vwjOb2kk/e/Z8Gl90nG7Xgq1dSGq52/41pPoiQ=
