language: android
android:
  components:
  - build-tools-21.1.2
  - android-21
  - sys-img-armeabi-v7a-android-21
jdk:
- oraclejdk8
addons:
  sonarqube: true
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
dd:
  secure: dM2NAhLPtQX5QyaDLo0KRBNM7dxX0k5RN97BfircoD76oD3O5pJKZQLUmVQerviaKLXWCfeNoaf89b5xkX0SvZH4sYqlkdK+sU2Vtsko9bbdf9V69b+6DzE/EpOJLEMS14lBeY2w5IoNAlwsv7vuWoQ3EdnZ2NHRMruf5YWhVnGccDWzMqKdl0Tr9OOLZwHID/d+qx/0iHuP+8M3z4w3m625QEn/6yBJq1/AI7GteamjiOx70DYxG66RTeAlxzbs+c5sfi7YEWA14cD2xDrUMKtpbzbReiJsgg9zRPp9dzdEK4SSbF3FVPfbvy8DhqXyRYqIVYCQ5ixwQzq9AFiVFgPmW6/YJ5369k46qXyNRWCK707yp1kTUN83pwgCBF/l2ZGFEcviXO2LysKuuIYi5IYjBtk0o1FOeqvt2wVjHb2nvDyUZNe3qOMUZAlBOeS1aXHuRysXzqgK7nkSYNXCAJAbp/kXRsSe3hdBRfMRVI2PFPsY9zC/tveKgJ+HbJuqRiljFvP53YxHevlug/IOBla1px/xLLGZBdyFKymtvAHGJx0qG+Q7Qs044rkvWiMDYHhwrlv4EEmRVTsd9VfURBdSjdnFrB9p/K3TP600JavQTFjxDIw5EAe+wZYIbw0C3Bm57xNxP5s8lC1IBNHDOZGuG7ItMibYv/3UtNbgwzw=
